# Generated by Django 5.0.1 on 2024-01-08 23:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('nome', models.CharField(max_length=255)),
                ('nome_artistico', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('site', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(blank=True, max_length=50)),
                ('sexo', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('nome_evento', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('tipo', models.CharField(blank=True, max_length=255)),
                ('ano_inicio', models.IntegerField(blank=True, null=True)),
                ('nacionalidade', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('titulo', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('titulo_pt', models.CharField(blank=True, max_length=255)),
                ('titulo_original', models.CharField(blank=True, max_length=255)),
                ('genero', models.CharField(blank=True, max_length=255)),
                ('ano', models.IntegerField(blank=True, null=True)),
                ('produtor', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Ator',
            fields=[
                ('nome_artistico', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app_cadastro_filmes.pessoa')),
                ('td_filmes_a', models.IntegerField(blank=True, null=True)),
                ('ano_a', models.IntegerField(blank=True, null=True)),
                ('td_premios_a', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Diretor',
            fields=[
                ('nome_artistico', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app_cadastro_filmes.pessoa')),
                ('td_filmes_d', models.IntegerField(blank=True, null=True)),
                ('ano_d', models.IntegerField(blank=True, null=True)),
                ('td_premios_d', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Roteirista',
            fields=[
                ('nome_artistico', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app_cadastro_filmes.pessoa')),
                ('td_filmes_r', models.IntegerField(blank=True, null=True)),
                ('ano_r', models.IntegerField(blank=True, null=True)),
                ('td_premios_r', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Edicao',
            fields=[
                ('id_edicao', models.IntegerField(primary_key=True, serialize=False)),
                ('data', models.CharField(blank=True, max_length=255)),
                ('localizacao', models.CharField(blank=True, max_length=255)),
                ('vencedor', models.CharField(blank=True, max_length=255)),
                ('premio', models.CharField(blank=True, max_length=255)),
                ('categoria', models.CharField(blank=True, max_length=255)),
                ('nome_artistico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_cadastro_filmes.pessoa')),
                ('nome_evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_cadastro_filmes.evento')),
            ],
        ),
        migrations.CreateModel(
            name='Informacao',
            fields=[
                ('id_informacao', models.IntegerField(primary_key=True, serialize=False)),
                ('local_estreia', models.CharField(blank=True, max_length=255)),
                ('sala_exibicao', models.CharField(blank=True, max_length=255)),
                ('arrecadacao_primeiro_ano', models.BigIntegerField(blank=True, null=True)),
                ('arrecadacao_total', models.BigIntegerField(blank=True, null=True)),
                ('id_edicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_cadastro_filmes.edicao')),
                ('titulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_cadastro_filmes.filme')),
            ],
        ),
        migrations.CreateModel(
            name='EJuri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_edicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_cadastro_filmes.edicao')),
                ('nome_artistico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_cadastro_filmes.pessoa')),
            ],
            options={
                'unique_together': {('nome_artistico', 'id_edicao')},
            },
        ),
        migrations.CreateModel(
            name='Indicado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_edicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_cadastro_filmes.edicao')),
                ('nome_artistico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_cadastro_filmes.pessoa')),
                ('titulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_cadastro_filmes.filme')),
            ],
            options={
                'unique_together': {('nome_artistico', 'id_edicao', 'titulo')},
            },
        ),
        migrations.CreateModel(
            name='Ocorre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_edicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_cadastro_filmes.edicao')),
                ('nome_evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_cadastro_filmes.evento')),
            ],
            options={
                'unique_together': {('nome_evento', 'id_edicao')},
            },
        ),
        migrations.CreateModel(
            name='Participa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_artistico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_cadastro_filmes.pessoa')),
                ('titulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_cadastro_filmes.filme')),
            ],
            options={
                'unique_together': {('nome_artistico', 'titulo')},
            },
        ),
        migrations.CreateModel(
            name='Possui',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_informacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_cadastro_filmes.informacao')),
                ('titulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_cadastro_filmes.filme')),
            ],
            options={
                'unique_together': {('titulo', 'id_informacao')},
            },
        ),
    ]
