# Generated by Django 5.0.1 on 2024-01-12 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('Nome', models.CharField(max_length=255)),
                ('Nome_Artístico', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('Site', models.CharField(max_length=255)),
                ('Status', models.CharField(max_length=50)),
                ('Sexo', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Pessoa',
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('NomeEvento', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('Tipo', models.CharField(max_length=255)),
                ('Ano_Inicio', models.IntegerField()),
                ('Nacionalidade', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Evento',
            },
        ),
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('Título', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('Título_Pt', models.CharField(max_length=255)),
                ('Título_Original', models.CharField(max_length=255)),
                ('Gênero', models.CharField(max_length=255)),
                ('Ano', models.IntegerField()),
                ('Produtor', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Filme',
            },
        ),
        migrations.CreateModel(
            name='Ator',
            fields=[
                ('Nome_Artístico', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app_cadastro_filmes.pessoa')),
                ('tdFilmesA', models.IntegerField()),
                ('Ano_A', models.IntegerField()),
                ('tdPremiosA', models.IntegerField()),
            ],
            options={
                'db_table': 'Ator',
            },
        ),
        migrations.CreateModel(
            name='Diretor',
            fields=[
                ('Nome_Artístico', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app_cadastro_filmes.pessoa')),
                ('tdFilmesD', models.IntegerField()),
                ('Ano_D', models.IntegerField()),
                ('tdPremiosD', models.IntegerField()),
            ],
            options={
                'db_table': 'Diretor',
            },
        ),
        migrations.CreateModel(
            name='Roteirista',
            fields=[
                ('Nome_Artístico', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app_cadastro_filmes.pessoa')),
                ('tdFilmesR', models.IntegerField()),
                ('Ano_R', models.IntegerField()),
                ('tdPremiosR', models.IntegerField()),
            ],
            options={
                'db_table': 'Roteirista',
            },
        ),
        migrations.CreateModel(
            name='Edição',
            fields=[
                ('ID_Edição', models.IntegerField(primary_key=True, serialize=False)),
                ('Data', models.CharField(max_length=255)),
                ('Localização', models.CharField(max_length=255)),
                ('Vencedor', models.CharField(max_length=255)),
                ('Premio', models.CharField(max_length=255)),
                ('Categoria', models.CharField(max_length=255)),
                ('Nome_Artístico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_cadastro_filmes.pessoa')),
                ('NomeEvento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_cadastro_filmes.evento')),
            ],
            options={
                'db_table': 'Edição',
            },
        ),
        migrations.CreateModel(
            name='Informação',
            fields=[
                ('ID_Informação', models.IntegerField(primary_key=True, serialize=False)),
                ('Local_Estreia', models.CharField(max_length=255)),
                ('Sala_Exibição', models.CharField(max_length=255)),
                ('Arrecadação_Primeiro_Ano', models.BigIntegerField()),
                ('Arrecadação_Total', models.BigIntegerField()),
                ('ID_Edição', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_cadastro_filmes.edição')),
                ('Título', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_cadastro_filmes.filme')),
            ],
            options={
                'db_table': 'Informação',
            },
        ),
        migrations.CreateModel(
            name='Indicado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_Edição', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_cadastro_filmes.edição')),
                ('Nome_Artístico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_cadastro_filmes.pessoa')),
                ('Título', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_cadastro_filmes.filme')),
            ],
            options={
                'db_table': 'Indicado',
                'unique_together': {('Nome_Artístico', 'ID_Edição', 'Título')},
            },
        ),
        migrations.CreateModel(
            name='Ocorre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_Edição', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_cadastro_filmes.edição')),
                ('NomeEvento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_cadastro_filmes.evento')),
            ],
            options={
                'db_table': 'Ocorre',
                'unique_together': {('NomeEvento', 'ID_Edição')},
            },
        ),
        migrations.CreateModel(
            name='Participa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome_Artístico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_cadastro_filmes.pessoa')),
                ('Título', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_cadastro_filmes.filme')),
            ],
            options={
                'db_table': 'Participa',
                'unique_together': {('Nome_Artístico', 'Título')},
            },
        ),
        migrations.CreateModel(
            name='Possui',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_Informação', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_cadastro_filmes.informação')),
                ('Título', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_cadastro_filmes.filme')),
            ],
            options={
                'db_table': 'Possui',
                'unique_together': {('Título', 'ID_Informação')},
            },
        ),
        migrations.CreateModel(
            name='ÉJuri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_Edição', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_cadastro_filmes.edição')),
                ('Nome_Artístico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_cadastro_filmes.pessoa')),
            ],
            options={
                'db_table': 'ÉJuri',
                'unique_together': {('Nome_Artístico', 'ID_Edição')},
            },
        ),
    ]
